version: 0
os: linux
files:
  - source: /build/libs/hola.war
    destination: /opt/tomcat/webapps
  - source: /tmp/codigo
    destination: /opt/tomcat
hooks:
  BeforeInstall:
    - location: codedeploy-scripts/beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root